### PR TITLE
add bert distill

### PR DESCRIPTION
**Pull request by 1049451037**
I met two problems when I try to add distillation.

* First, I don't know how to load a pretrained checkpoint **beyond** official models.
* Second, I need **two** tokenizers to train distilled model.

For now, I use bert-large as teacher and bert-base as student. The above two problems are OK because they are both official models and share a same tokenizer. But for other cases, the problems should be concerned.

### CODE REVIEW

**Comment by Sleepychord** [comment]
First, for your question:
1. you can define a model class and use NewClass.from_pretrained(args, 'a name'). I will add a dynamic loading function in the next version.
2. it is possible to record the tokenizer on your own, and re-get_tokenizer by passing an args with different tokenizer_type
```python
a = AutoModel.from_pretrained(args, 'a')
tka = get_tokenizer(a)
b = AutoModel.from_pretrained(args, 'b')
tkb = get_tokenizer(b)
# although after that get_tokenizer() returns tkb.
```

comments:
1. In most time, distilling begins with an untrained student. So why need two tokenizers? 
2. Could you make the distill a general thing? I mean add it to the SwissArmyTransformer/model.

**Comment by 1049451037** [comment]
1. Both trained teacher and untrained student need a tokenizer. When their tokenizers are different, we will need two tokenizers. And in `training_main` function, it is not well defined.
2. Yes, I can make it a general one, but the model loading and tokenizer problems should be tackled.

**Comment by Sleepychord** [comment]
hi, for model loading,  I don't fully understand why ` NewClass.from_pretrained(args, 'a name')` doesn't apply. 
To load a recent trained model, you can `from_pretrained(args, 'experiment_name_with_time', home_path='checkpoint_folder')

**Comment by 1049451037** [comment]
Oh... I see. I will try it.

**Comment by 1049451037** [comment]
@Sleepychord I tried to load it but failed.

```
AttributeError: 'Namespace' object has no attribute 'max_sequence_length'
```

It seems that the model_config.json is not complete.

**Pull request closed without merging**
