### PR TITLE
Add GLM-130B model

### PR DESCRIPTION
**Pull request by Sengxian**

### CODE REVIEW

**Comment by 1049451037** [comment]
There are three points to modify:

1. `position_embeddings.py` should be under `model/position_embedding/` folder, instead of `model/official folder`.
2. You'd better add a README.md under your glm-130b example folder, since I cannot run your example by running `bash scripts/generate_glm.sh`, where `cannot import name 'GLM130B' from 'SwissArmyTransformer.model'` is reported.
3. You should add your model url into `SwissArmyTransformer/resources/urls.py` to support `from_pretrained` function.

**Comment by Sengxian** [comment]
1. Fixed in

**Comment by Sengxian** [comment]
1. Fixed
2. This is because your python interpreter does not have the SwissArmyTransformer in this PR as the source directory. Running `pip install -e .` solves this issue. 
3. Due to the large file size (~260GB) and other considerations, we cannot provide a direct download link of the GLM-130B model checkpoint. We will provide an application form later for the model.

@1049451037

**Comment by hanyullai** [comment]
For point 2, we've added GLM130B in __init__ file and commit it.

**Comment by 1049451037** [comment]
I think your modification made existing code collapse. For example, here is the error when I run example/bert by `bash scripts/finetune_boolq.sh`

```bash
building ClassificationModel model ...                                                                   Traceback (most recent call last):                                                                       
  File "finetune_bert_boolq.py", line 89, in <module>                                                    
    device=torch.cuda.current_device() if args.use_gpu_initialization else torch.device('cpu')               model, args = ClassificationModel.from_pretrained(args, args.md_type)TypeError
:   File "/home/lvqingsong/new/SwissArmyTransformer-1/SwissArmyTransformer/model/base_model.py", line 154
, in from_pretrained                                                                                     
unsupported operand type(s) for ** or pow(): 'torch.device' and 'dict' 
```

**Pull request merged**
